# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0004_auto_20161123_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(db_index=True, default=0, verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433')),
                ('question', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='ask.Question', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
            ],
            options={
                'verbose_name': '\u0420\u0435\u0439\u0442\u0438\u043d\u0433 \u043e\u0442\u0432\u0435\u0442\u0430',
                'verbose_name_plural': '\u0420\u0435\u0439\u0442\u0438\u043d\u0433 \u043e\u0442\u0432\u0435\u0442\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(db_index=True, default=0, verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433')),
                ('question', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='ask.Question', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
            ],
            options={
                'verbose_name': '\u0420\u0435\u0439\u0442\u0438\u043d\u0433 \u0432\u043e\u043f\u0440\u043e\u0441\u0430',
                'verbose_name_plural': '\u0420\u0435\u0439\u0442\u0438\u043d\u0433 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432',
            },
        ),
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='question',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
