# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 06:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0006_auto_20161205_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': '\u041e\u0442\u0432\u0435\u0442', 'verbose_name_plural': '\u041e\u0442\u0432\u0435\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '\u041f\u0440\u043e\u0444\u0438\u043b\u044c', 'verbose_name_plural': '\u041f\u0440\u043e\u0444\u0438\u043b\u0438'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441', 'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b'},
        ),
        migrations.AlterModelOptions(
            name='questionlike',
            options={'verbose_name': '\u0420\u0435\u0439\u0442\u0438\u043d\u0433 \u0432\u043e\u043f\u0440\u043e\u0441\u0430', 'verbose_name_plural': '\u0420\u0435\u0439\u0442\u0438\u043d\u0433 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '\u0422\u044d\u0433', 'verbose_name_plural': '\u0422\u044d\u0433\u0438'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date',
        ),
        migrations.AddField(
            model_name='question',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='\u041a\u043e\u0440\u0440\u0435\u043a\u0442\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Question', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=b'uploads/user_2.png', upload_to=b'uploads'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='information',
            field=models.TextField(default=b'My info', verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='ask.Tag', verbose_name='\u0422\u044d\u0433'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='style_number',
            field=models.IntegerField(default=1, verbose_name='\u041d\u043e\u043c\u0435\u0440'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u0422\u0435\u0433'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
