# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0007_auto_20161205_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='created',
            new_name='data',
        ),
    ]
