# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0008_auto_20161205_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlike',
            name='is_disliked',
        ),
    ]
